version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: xbpneus
      POSTGRES_USER: xbp
      POSTGRES_PASSWORD: xbp123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      DATABASE_URL: postgres://xbp:xbp123@db:5432/xbpneus
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
      SECRET_KEY: dev-secret-change-me
    volumes:
      - ./:/app
    depends_on:
      - db
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    environment:
      VITE_API_BASE: http://localhost:8000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    command: >
      sh -c "npm install && npm run dev -- --host"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.gateway
    environment:
      DJANGO_URL: http://web:8000
    depends_on:
      - web
    ports:
      - "9000:9000"

volumes:
  db_data:
