# Render Blueprint for XBPNEUS
# Docs: https://render.com/docs/blueprint-spec
previews:
  generation: automatic

databases:
  - name: xbpneus-db
    plan: starter
    region: virginia
    databaseName: xbpneus
    user: xbpneus

services:
  # Django backend (Gunicorn)
  - type: web
    name: xbpneus-api
    runtime: python
    branch: main
    plan: starter
    region: virginia
    rootDir: .
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - fromGroup: xbpneus-common
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DATABASE_URL
        fromDatabase:
          name: xbpneus-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: xbpneus-kv
          property: connectionString

  # Frontend static site (Vite/React or similar)
  - type: web
    name: xbpneus-frontend
    runtime: static
    branch: main
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - fromGroup: xbpneus-common
      # If your frontend needs the public API URL, set this after the first deploy:
      # - key: VITE_API_BASE_URL
      #   value: https://xbpneus-api.onrender.com

  # Redis-compatible Key Value store
  - type: keyvalue
    name: xbpneus-kv
    plan: starter
    region: virginia
    # ipAllowList: []  # keep private; leave empty for internal only

envVarGroups:
  - name: xbpneus-common
    envVars:
      - key: SECRET_KEY
        generateValue: true   # Django secret
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        sync: false           # set your onrender.com/custom domain here after first deploy
      - key: TIME_ZONE
        value: America/Sao_Paulo
      - key: PYTHONUNBUFFERED
        value: "1"
      # Optional observability
      - key: SENTRY_DSN
        sync: false
      # Optional CORS
      - key: CORS_ALLOWED_ORIGINS
        sync: false
