services:
  # Backend Django
  - type: web
    name: xbpneus-backend
    env: python
    region: oregon
    plan: free
    branch: master
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --threads 2 --timeout 120"
    healthCheckPath: /healthz/

    envVars: 
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: config.render_production
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: xbpneus-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: xbpneus-redis
          property: connectionString
      - key: DJANGO_DEBUG
        value: False
      - key: SESSION_COOKIE_SECURE
        value: True
      - key: CSRF_COOKIE_SECURE
        value: True
      - key: SECURE_SSL_REDIRECT
        value: False
      - key: SECURE_HSTS_SECONDS
        value: 31536000
      - key: SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: True
      - key: SECURE_HSTS_PRELOAD
        value: True
      - key: PAGE_SIZE
        value: 20
      - key: CORS_ALLOWED_ORIGINS
        value: https://xbpneus-frontend.onrender.com
      - key: CORS_ALLOW_CREDENTIALS
        value: True

  # Frontend React (Static Site)
  - type: web
    name: xbpneus-frontend
    env: static
    branch: master
    rootDir: frontend
    buildCommand: "npm ci --include=dev && npm run build"
    staticPublishPath: ./dist
    
    envVars: 
      - key: NODE_VERSION
        value: 22.13.0
      - key: VITE_API_URL
        value: https://xbpneus-backend.onrender.com
      - key: NODE_ENV
        value: production

  # Redis (Key Value)
  - type: keyvalue
    name: xbpneus-redis
    region: oregon
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all connections

databases:
  - name: xbpneus-db
    databaseName: xbpneus
    user: xbpneus
    region: oregon
    plan: free

